version: '3.9'

services:
  redis:
    image: redis/redis-stack
    container_name: redis
    volumes:
      - ./data:/data
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: always
    networks:
      - redis

networks:
  redis:
    name: redis
