using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ShelfApi.Domain.ConfigurationAggregate;
using ShelfApi.Infrastructure.Extensions;

namespace ShelfApi.Infrastructure.Data;

public class ConfigsConfiguration : IEntityTypeConfiguration<Configs>
{
    public void Configure(EntityTypeBuilder<Configs> builder)
    {
        builder.ConfigureOrders();
        builder.ConfigureKey(autoGenerated: false);
        builder.ConfigureCreatedAt();
        builder.ConfigureModifiedAt();

        builder.Property(x => x.EnvironmentName)
            .HasConversion<string>()
            .HasColumnType("varchar(60)");

        builder.Property(x => x.Category)
            .HasConversion<string>()
            .HasColumnType("varchar(60)");
    }
}
