using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ShelfApi.Domain.Common;
using System.Reflection;

namespace ShelfApi.Infrastructure.Extensions;

public static class SqlConfigurationExtensions
{
    public static void SetOrderForAllProperties<T>(this EntityTypeBuilder<T> builder, int startOrderNumber = 100) where T : class
    {
        var properties = builder.Metadata.ClrType
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Select(x => x.Name)
            .ToList();

        foreach (var property in properties)
        {
            builder.Property(property).HasColumnOrder(startOrderNumber);
            startOrderNumber++;
        }
    }

    public static void ConfigureKey<T>(this EntityTypeBuilder<T> builder, bool autoGenerated = false) where T : class
    {
        builder.HasKey(nameof(BaseModel<object>.Id));

        builder.Property(nameof(BaseModel<object>.Id))
            .HasColumnOrder(1);

        if (autoGenerated)
            builder.Property(nameof(BaseModel<object>.Id))
                .ValueGeneratedOnAdd();
        else
            builder.Property(nameof(BaseModel<object>.Id))
                .ValueGeneratedNever();
    }

    public static void ConfigureCreatedAt<T>(this EntityTypeBuilder<T> builder) where T : class
    {
        builder.Property<DateTime>(nameof(BaseModel<object>.CreatedAt))
            .IsRequired(true)
            .HasColumnOrder(1000)
            .HasDefaultValueSql("SYSUTCDATETIME()");
    }

    public static void ConfigureModifiedAt<T>(this EntityTypeBuilder<T> builder) where T : class
    {
        builder.Property<DateTime?>(nameof(BaseModel<object>.ModifiedAt))
            .HasColumnOrder(1001)
            .IsRequired(false);
    }
}
