using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using ShelfApi.Domain.UserAggregate;
using ShelfApi.Infrastructure.Extensions;

namespace ShelfApi.Infrastructure.Data;

public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users");

        builder.ConfigureOrders();
        builder.ConfigureKey(autoGenerated: false);
        builder.ConfigureCreatedAt();
        builder.ConfigureModifiedAt();

        builder.Property(x => x.IsAdmin);
    }
}